service: basic-aws-lambda

provider:
  name: aws
  runtime: python3.8
  versionFunction: false
  memorySize: 128
  region: us-east-2

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
        path: echo/hello
        method: get
