service: basic-aws-lambda

provider:
  name: aws
  region: eu-west-1
  runtime: python3.8
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:QUery
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"


functions:
  read:
    handler: src/handler.get_all
    events:
      - http: get read
  insert:
    handler: src/handler.insert_item
    events:
      - http: post insert
