service: basic-aws-lambda

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  region: eu-north-1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
        path: echo/hello
        method: get
