#  ref: https://github.com/mirrorhanyu/serverless-github-action-python
name: Deploy main branch

on:
  push:
    branches:
      - main     

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@main
      - name: npm install
        uses: actions/npm@main
        with:
          args: install
      - name: serverless deploy
        uses: serverless-github-action-python@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}